"use client";import{useState}from"react";
const services=[["OUTSIDE","99","Exterior wash, wheels, tires, glass and a crisp finish."],["INSIDE","159","Vacuum, surfaces, glass and a thorough interior clean."],["FULL","229","Complete interior + exterior detail.","MOST POPULAR"],["RESET","329","A deeper reset for vehicles needing extra time and attention."]];
const faqs=[["Do you come to me?","Yes. PARKED. is mobile detailing built around your day. Choose home, work, or another suitable location."],["What do I need to provide?","We’ll confirm access and site requirements with your appointment so you know exactly what is needed."],["How long does a detail take?","It depends on the service, vehicle size and condition. We’ll provide an estimate when your appointment is confirmed."],["What about pet hair or heavy stains?","Tell us in your request. Pet hair, severe stains and excessive soil may require extra time and an adjusted quote."],["What if the weather is bad?","If conditions make service impractical or unsafe, we’ll coordinate a better time."],["Can you detail at work or an apartment?","Usually, provided the property permits it and the site is suitable. We’ll confirm before the appointment."],["Is the starting price always final?","Not always. Vehicle size and condition can affect the final quote. Any change is confirmed before work begins."],["How do I pay?","Payment details are confirmed with your appointment."]];
function Logo(){return <a className="logo" href="#">PARKED<span>.</span></a>}
function Options({vals,value,set}){return <div className="options">{vals.map(v=><button type="button" className={value===v?"on":""} onClick={()=>set(v)} key={v}>{v}<span>{value===v?"●":"○"}</span></button>)}</div>}
function Pane({n,title,children}){return <div className="pane"><div className="label">STEP {n} / 06</div><h2>{title}</h2>{children}</div>}
export default function Home(){const[faq,setFaq]=useState(null),[booking,setBooking]=useState(false),[step,setStep]=useState(0),[form,setForm]=useState({service:"FULL",vehicle:"Sedan / Coupe",location:"Home"});const upd=(k,v)=>setForm({...form,[k]:v});const open=(service)=>{if(service)upd("service",service);setBooking(true);setStep(0)};
return <main><header><Logo/><nav><a href="#services">Services</a><a href="#how">How it works</a><a href="#results">Results</a><a href="#faq">FAQ</a></nav><button onClick={()=>open()}>Book a Detail</button></header>
<section className="hero"><div className="eyebrow">MOBILE DETAILING · NORTHEAST OHIO</div><h1>STAY<br/>PARKED<span>.</span></h1><p>Professional detailing, wherever your car happens to be. Home. Work. Wherever. We bring what we need and handle the rest.</p><div className="actions"><button onClick={()=>open()}>Book a Detail →</button><a href="#services">See Services</a></div><div className="trust"><span>● MOBILE</span><span>● WE COME TO YOU</span><span>● INSIDE + OUT</span></div></section>
<section id="how" className="section dark"><div className="label">HOW IT WORKS</div><h2>You park it.<br/>We handle the rest.</h2><div className="steps">{[["01","BOOK","Choose your vehicle, service, location and preferred time."],["02","PARK","Leave your vehicle at home, work, or wherever you’re spending your day."],["03","DONE","We detail it on-site. You get your keys back clean."]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section id="services" className="section"><div className="label">SERVICES</div><div className="sectionHead"><h2>Simple choices.<br/>Clean results.</h2><p>Starting prices. Final price depends on vehicle size and condition.</p></div><div className="cards">{services.map(s=><article className={s[3]?"featured":""} key={s[0]}>{s[3]&&<em>{s[3]}</em>}<h3>{s[0]}</h3><div className="price"><small>FROM</small> {"$"+s[1]}</div><p>{s[2]}</p><button onClick={()=>open(s[0])}>Choose {s[0].toLowerCase()} →</button></article>)}</div><p className="addons"><b>Need more?</b> Pet hair · severe stains · excessive soil · engine bay · headlights · paint decontamination / polishing. Tell us what your vehicle needs when you request an appointment.</p></section>
<section className="section split"><div><div className="label">CONVENIENCE, BUILT IN</div><h2>Your driveway<br/>is our shop.</h2></div><div><p className="bigp">No drop-off. No waiting room. No losing half your day retrieving your car.</p><p>Book the service, park where you already need to be, and keep moving. We’ll confirm access and site requirements before your appointment.</p><button onClick={()=>open()}>Request an appointment →</button></div></section>
<section id="results" className="section results"><div className="label">RESULTS</div><h2>Clean speaks<br/>for itself.</h2><div className="gallery"><div><span>BEFORE</span></div><div><span>AFTER</span></div></div><p>Real customer results coming soon. No stock transformations. No fake reviews.</p></section>
<section id="faq" className="section faq"><div><div className="label">FAQ</div><h2>Before you<br/>get parked.</h2></div><div>{faqs.map((x,i)=><article key={x[0]}><button onClick={()=>setFaq(faq===i?null:i)}><span>{x[0]}</span><b>{faq===i?"−":"+"}</b></button>{faq===i&&<p>{x[1]}</p>}</article>)}</div></section>
<section className="cta"><div className="label">READY WHEN YOU ARE</div><h2>Stay parked<span>.</span></h2><p>Choose your service and tell us where the car will be.</p><button onClick={()=>open()}>Book a Detail →</button></section>
<footer><Logo/><div><a href="#services">Services</a><a href="#how">How it works</a><a href="#faq">FAQ</a><button onClick={()=>open()}>Book</button></div><p>Mobile detailing · Northeast Ohio<br/>© 2026 PARKED.</p></footer><button className="mobileBook" onClick={()=>open()}>Book a Detail →</button>
{booking&&<div className="modal"><div className="book"><button className="x" onClick={()=>setBooking(false)}>×</button>{step<6&&<div className="progress"><span style={{width:(step+1)/6*100+"%"}}/></div>}
{step===0&&<Pane n="01" title="What are we cleaning?"><Options vals={services.map(x=>x[0])} value={form.service} set={v=>upd("service",v)}/></Pane>}
{step===1&&<Pane n="02" title="What do you drive?"><Options vals={["Sedan / Coupe","SUV / Truck","3-Row / Large"]} value={form.vehicle} set={v=>upd("vehicle",v)}/></Pane>}
{step===2&&<Pane n="03" title="Where will you be parked?"><Options vals={["Home","Work","Other"]} value={form.location} set={v=>upd("location",v)}/><input placeholder="Service address" value={form.address||""} onChange={e=>upd("address",e.target.value)}/></Pane>}
{step===3&&<Pane n="04" title="When works best?"><input type="date" value={form.date||""} onChange={e=>upd("date",e.target.value)}/><select value={form.time||""} onChange={e=>upd("time",e.target.value)}><option value="">Preferred time window</option><option>Morning</option><option>Afternoon</option><option>Evening</option></select><p className="note">This is a request. We’ll confirm availability with you.</p></Pane>}
{step===4&&<Pane n="05" title="How can we reach you?"><input placeholder="Name" value={form.name||""} onChange={e=>upd("name",e.target.value)}/><input placeholder="Mobile phone" value={form.phone||""} onChange={e=>upd("phone",e.target.value)}/><input type="email" placeholder="Email" value={form.email||""} onChange={e=>upd("email",e.target.value)}/><textarea placeholder="Pet hair, stains, excessive soil, special concerns..." value={form.notes||""} onChange={e=>upd("notes",e.target.value)}/></Pane>}
{step===5&&<Pane n="06" title="Review your request"><div className="review"><b>{form.service}</b><span>{form.vehicle}</span><span>{form.location}{form.address?" · "+form.address:""}</span><span>{form.date||"Preferred date not set"}{form.time?" · "+form.time:""}</span><span>{form.name||"Contact name"} · {form.phone||form.email||"Contact info"}</span></div><p className="note">Starting price may change with vehicle size or condition. We’ll confirm before work begins.</p></Pane>}
{step===6&&<div className="success"><div className="dot">✓</div><div className="label">REQUEST RECEIVED</div><h2>You’re parked<span>.</span></h2><p>Your preferred appointment details have been captured. PARKED. will confirm before service.</p><button onClick={()=>setBooking(false)}>Done</button></div>}
{step<6&&<div className="bookNav"><button disabled={step===0} onClick={()=>setStep(step-1)}>Back</button><button onClick={()=>setStep(step+1)}>{step===5?"Request Appointment":"Continue →"}</button></div>}</div></div>}</main>}